name: Comment on pylint issue comparison

on: [pull_request_target]

jobs:
  lint_comparison:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    # install python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    # checkout the PR
    - uses: actions/checkout@v3
      with:
        ref: "refs/pull/${{ github.event.number }}/merge"
    # cache the pip step for speed
    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
    # install the dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[testing]
    # make the report
    - uses: SJShaw/pylint-compare@main
      with:
        targets: antismash *.py
        install_pylint: false
